[package]
name = "path"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
priority-queue = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[lib]
path = "src/path.rs"
