interface ClassroomTechInstructions {
  [key: string]: string;
}

export const classroomTechInstructions: ClassroomTechInstructions = {
  'BH-36A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_36a.pdf',
  'BH-A51':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_a51.pdf',
  'BH-A53':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_a53.pdf',
  'BH-136E':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_136e.pdf',
  'BH-154A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/bh_154a.pdf',
  'BH-235A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_235a.pdf',
  'BH-235B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_235b.pdf',
  'BH-237B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_237b.pdf',
  'BH-255A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/baker_255a.pdf',
  'CFA-102':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/cfa_102.pdf',
  'DH-A302':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_a302.pdf',
  'DH-1112':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_1112.pdf',
  'DH-1117':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_1117.pdf',
  'DH-1209':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_1209.pdf',
  'DH-1211':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_1211.pdf',
  'DH-1212':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_1212.pdf',
  'DH-2105':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_2105.pdf',
  'DH-2122':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_2122.pdf',
  'DH-2210':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_2210.pdf',
  'DH-2302':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_2302.pdf',
  'DH-2315':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/doherty_2315.pdf',
  'GHC-4307':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/gates_4307.pdf',
  'GHC-4401':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/gates_4401.pdf',
  'HOA-107':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/hoa_107.pdf',
  'HOA-160':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/hoa_160.pdf',
  'HH-B103':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/hamerschlag_b103.pdf',
  'HH-B131':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/hamerschlag_b131.pdf',
  'MM-A14':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/mmch_a14.pdf',
  'MM-103':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/mmch_103.pdf',
  'MI-348':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/mellon_348.pdf',
  'MI-355':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/mellon_355.pdf',
  'MI-448':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/mellon_448.pdf',
  'PH-A18A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a18a.pdf',
  'PH-A18B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a18b.pdf',
  'PH-A18C':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a18c.pdf',
  'PH-A19':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a19.pdf',
  'PH-A19A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a19a.pdf',
  'PH-A19C':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a19c.pdf',
  'PH-A19D':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a19d.pdf',
  'PH-A20':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a20.pdf',
  'PH-A20A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a20a.pdf',
  'PH-A21':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a21.pdf',
  'PH-A21A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a21a.pdf',
  'PH-A22':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_a22.pdf',
  'PH-100':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porterhall_100.pdf',
  'PH-125B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_125b.pdf',
  'PH-125C':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_125c.pdf',
  'PH-125D':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_125d.pdf',
  'PH-126A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_126a.pdf',
  'PH-225B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_225b.pdf',
  'PH-226A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_226a.pdf',
  'PH-226B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_226b.pdf',
  'PH-226C':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/porter_226c.pdf',
  'POS-A35':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_a35.pdf',
  'POS-145':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_145.pdf',
  'POS-146':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_146.pdf',
  'POS-147':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_147.pdf',
  'POS-151':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_151.pdf',
  'POS-152':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_152.pdf',
  'POS-153':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/posner_153.pdf',
  'SH-105':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/scaife-hall-105.pdf',
  'SH-234':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/scaife-hall-234.pdf',
  'SH-236':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/scaife-hall-236.pdf',
  'SH-238':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/scaife-hall-238.pdf',
  'TEP-1308':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/tepper-1308.pdf',
  'TEP-1309':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/tepper-1309.pdf',
  'TEP-3500':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/tepper-quad-3500.pdf',
  'WEH-4623':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_4623.pdf',
  'WEH-4625':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_4625.pdf',
  'WEH-4707':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_4707.pdf',
  'WEH-4708':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_4708.pdf',
  'WEH-4709':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_4709.pdf',
  'WEH-5302':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5302.pdf',
  'WEH-5304':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5304.pdf',
  'WEH-5310':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5310.pdf',
  'WEH-5312':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5312.pdf',
  'WEH-5316':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5316.pdf',
  'WEH-5320':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5320.pdf',
  'WEH-5328':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5328.pdf',
  'WEH-5403':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_5403.pdf',
  'WEH-5409':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_5409.pdf',
  'WEH-5415':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5415.pdf',
  'WEH-5421':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wh_5421.pdf',
  'WEH-6403':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_6403.pdf',
  'WEH-6423':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_6423.pdf',
  'WEH-7500':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_7500.pdf',
  'WEH-8427':
    'https://www.cmu.edu/computing/services/teach-learn/tes/classrooms/guides/wean_8427.pdf',
  'BH-140A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/baker140a.pdf',
  'BH-140B':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/baker140b.pdf',
  'CFA-317':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/cfa_317.pdf',
  'CFA-318':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/cfa323-poster.pdf',
  'CH-100A':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/cyert100a.pdf',
  'WEH-5201':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/wh_5201.pdf',
  'WEH-5202':
    'https://www.cmu.edu/computing/services/teach-learn/tes/computer-labs/guides/wean5207-poster.pdf',
};
