FROM oven/bun:latest

# Install OpenSSL
Run apt-get update -y && apt-get install -y openssl

# Copy everything
COPY . .

# # Install vault
# brew tap hashicorp/tap
# brew install hashicorp/tap/vault

# # Install jq
# brew install jq
