#!/usr/bin/env zsh
set -e
editorconfig-checker --exclude '(^LICENSE|^apps/rust-server/.*)'
bun run syncpack
# bunx markdownlint-cli2
bun run check
if git diff --cached --name-only | grep -q '^apps/dataflow/'; then
  (cd apps/dataflow && uv run lint)
fi
