/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapFloorCodeRouteImport } from './routes/map/$floorCode'
import { Route as FloorsFloorCodeRouteImport } from './routes/floors/$floorCode'
import { Route as BuildingsBuildingCodeRouteImport } from './routes/buildings/$buildingCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapFloorCodeRoute = MapFloorCodeRouteImport.update({
  id: '/map/$floorCode',
  path: '/map/$floorCode',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorsFloorCodeRoute = FloorsFloorCodeRouteImport.update({
  id: '/floors/$floorCode',
  path: '/floors/$floorCode',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsBuildingCodeRoute = BuildingsBuildingCodeRouteImport.update({
  id: '/buildings/$buildingCode',
  path: '/buildings/$buildingCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buildings/$buildingCode': typeof BuildingsBuildingCodeRoute
  '/floors/$floorCode': typeof FloorsFloorCodeRoute
  '/map/$floorCode': typeof MapFloorCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildings/$buildingCode': typeof BuildingsBuildingCodeRoute
  '/floors/$floorCode': typeof FloorsFloorCodeRoute
  '/map/$floorCode': typeof MapFloorCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buildings/$buildingCode': typeof BuildingsBuildingCodeRoute
  '/floors/$floorCode': typeof FloorsFloorCodeRoute
  '/map/$floorCode': typeof MapFloorCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buildings/$buildingCode'
    | '/floors/$floorCode'
    | '/map/$floorCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buildings/$buildingCode'
    | '/floors/$floorCode'
    | '/map/$floorCode'
  id:
    | '__root__'
    | '/'
    | '/buildings/$buildingCode'
    | '/floors/$floorCode'
    | '/map/$floorCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingsBuildingCodeRoute: typeof BuildingsBuildingCodeRoute
  FloorsFloorCodeRoute: typeof FloorsFloorCodeRoute
  MapFloorCodeRoute: typeof MapFloorCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$floorCode': {
      id: '/map/$floorCode'
      path: '/map/$floorCode'
      fullPath: '/map/$floorCode'
      preLoaderRoute: typeof MapFloorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floors/$floorCode': {
      id: '/floors/$floorCode'
      path: '/floors/$floorCode'
      fullPath: '/floors/$floorCode'
      preLoaderRoute: typeof FloorsFloorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/$buildingCode': {
      id: '/buildings/$buildingCode'
      path: '/buildings/$buildingCode'
      fullPath: '/buildings/$buildingCode'
      preLoaderRoute: typeof BuildingsBuildingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingsBuildingCodeRoute: BuildingsBuildingCodeRoute,
  FloorsFloorCodeRoute: FloorsFloorCodeRoute,
  MapFloorCodeRoute: MapFloorCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
