name: Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    env:
      SYNC_GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
      CLERK_DEV_SECRET_KEY: ${{ secrets.CLERK_DEV_SECRET_KEY }}
      CLERK_DEV_ORG_ID: ${{ secrets.CLERK_DEV_ORG_ID }}
      CLERK_PROD_SECRET_KEY: ${{ secrets.CLERK_PROD_SECRET_KEY }}
      CLERK_PROD_ORG_ID: ${{ secrets.CLERK_PROD_ORG_ID }}
      KEYCLOAK_SERVER_URL: ${{ secrets.KEYCLOAK_SERVER_URL }}
      KEYCLOAK_USERNAME: ${{ secrets.KEYCLOAK_USERNAME }}
      KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_USER_REALM: ${{ secrets.KEYCLOAK_USER_REALM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Sync Script
        run: cd governance && pip3 install -r requirements.txt && python3 -m scripts.sync
